version: 2

models:
  - name: stg_customers
    description: This is description for the entire model (in this case stg_customers)
    columns: 
      - name: customer_id
        description: This is description for the specific column (in this case customer_id)
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns: 
      - name: status
        tests:
          - accepted_values:
              values:
                - completed
                - shipped
                - returned
                - placed
                - return_pending